apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: self-signed-ca
  namespace: cert-manager
spec:
  secretName: self-signed-ca
  subject:
    countries:
      - "US"
    organizationalUnits:
      - "Office"
    localities:
      - "Cary"
    provinces:
      - "NC"
    streetAddresses:
      - "244 Damsire Way"
    postalCodes:
      - "27513"
    organizations:
      - "Home"
  emailAddresses:
    - "siming.weng@gmail.com"
  dnsNames:
    - "simingweng.com"
  isCA: true
  issuerRef:
    name: self-signed
    kind: ClusterIssuer