apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server
spec:
  secretName: server-tls
  dnsNames:
    - "mtls-hello-server"
  issuerRef:
    name: self-signed-ca
    kind: ClusterIssuer